name: CI

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Todo: add Android and Linux build as matrix
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repository
        uses: actions/checkout@v2

      # - name: Set Qt version
      #   run: |
      #     echo qtver=5.15.2 >> $env:GITHUB_ENV
      #     echo qtpath=D:\Qt >> $env:GITHUB_ENV
      #     echo qtarch=win64_msvc2019_64 >> $env:GITHUB_ENV
      # - name: Cache Qt
      #   id: cache-qt
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ env.qtpath }}
      #     key: ${{ runner.os }}-Qt-${{ env.qtver }}-Cache2

      # - name: Download Qt
      #   uses: jurplel/install-qt-action@v2
      #   with:
      #     cached: ${{ steps.cache-qt.outputs.cache-hit }}
      #     version: ${{ env.qtver }}
      #     arch: ${{ env.qtarch }}
      #     dir: ${{ env.qtpath }}

      - name: Download ninja
        run: |
          mkdir build
          cd build
          curl -LO https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
          7z x ninja-win.zip
          echo "${env:GITHUB_WORKSPACE}\build\" >> $env:GITHUB_PATH
          
      - name: Download yasm
        run: |
          cd build
          curl -LO http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
          move-item yasm-1.3.0-win64.exe yasm.exe
          
      - name: Clone FFmpeg
        uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
          path: build/ffmpeg
          ref: release/4.4
          
      - name: Build ffmpeg
        run: |
          cd build/ffmpeg
          ./configure --disable-all --enable-avcodec --enable-decoder=h264 --enable-decoder=hevc --enable-hwaccel=h264_vaapi --enable-hwaccel=hevc_vaapi --target-os=win64 --arch=x86_64 --toolchain=msvc
          ls
          bash make
          bash make install
          
