name: CI

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Todo: add Android and Linux build as matrix
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir build
          cd build
          curl -LO https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
          7z x ninja-win.zip
          .\ninja.exe
          
          
