name: CI

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Todo: add Android and Linux build as matrix
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set Qt version
        run: |
          echo qtver=5.15.2 >> $env:GITHUB_ENV
          echo qtpath=D:\Qt >> $env:GITHUB_ENV
          echo qtarch=win64_msvc2019_64 >> $env:GITHUB_ENV

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ${{ env.qtpath }}
          key: ${{ runner.os }}-Qt-${{ env.qtver }}-Cache2

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.qtver }}
          arch: ${{ env.qtarch }}
          dir: ${{ env.qtpath }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          #bash scripts/appveyor-win.sh

